name: workflow

on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: akasai/github-action-test@feature/ts-lint
        with:
          config: 'tsconfig.json'
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'
