name: Checkout Action

on: [push]
#  pull_request:
#    - master

jobs:
  my_jobs:
    name: CheckoutAction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check ls
        run: echo `ls -la`
